### ISSUE TITLE
reminder for realease notes 2023.2: mention the `003_vlan_type_string` DB script

### ISSUE THREAD

**Issue by Alopalao** [kytos-ng/kytos-ng.github.io#62]
A reminder to mention `003_vlan_type_string` DB script that changes every `tag_type` to its string equivalent 

[kytos-ng/mef_eline#371](https://github.com/kytos-ng/mef_eline/pull/371)

**Comment by viniarck** [comment]
Closing this reminder in favor of https://github.com/kytos-ng/kytos-ng.github.io/issues/63 (it's unifying there)
